### ISSUE TITLE
Issue while adding extension in burp

### ISSUE THREAD

**Issue by sancelisso** [sting8k/BurpSuite_403Bypasser#5]
I get this error while loading extension from python file:

`java.lang.Exception: Failed to load Python interpreter from Jython JAR file
	at burp.e76.<init>(Unknown Source)
	at burp.f1z.a(Unknown Source)
	at burp.gvj.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by sting8k** [comment]
Hmm, I don't know why you got this error, try to load some of these extensions: [https://portswigger.net/burp/extender#SampleExtensions](https://portswigger.net/burp/extender#SampleExtensions). If you got same error, maybe the version of Jython or Burpsuite is out of date.

**Comment by Unknownghost12** [comment]
Sorry sir we will be with you shortly
