### ISSUE TITLE
Error while uploading the extension on Burp with the latest jython 2.7.2

### ISSUE THREAD

**Issue by cryptoknife** [sting8k/BurpSuite_403Bypasser#8]
SyntaxError: Non-ASCII character in file 'C:\Users\sbdefault\Desktop\Burp Custom Extensions\403bypasser.py', but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

	at org.python.core.Py.SyntaxError(Py.java:171)
	at org.python.core.ParserFacade.fixParseError(ParserFacade.java:105)
	at org.python.core.ParserFacade.parse(ParserFacade.java:190)
	at org.python.core.Py.compile_flags(Py.java:2232)
	at org.python.core.__builtin__.execfile_flags(__builtin__.java:527)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:287)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.ip.<init>(Unknown Source)
	at burp.xkf.a(Unknown Source)
	at burp.plh.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by cryptoknife** [comment]
Any updates so far?
